name: Developer Hub
markdown: kramdown
highlighter: rouge
safe: true
baseurl: /book
exclude: ['.ruby-version', 'node_modules', 'package.json', 'bower.json']
gems:
  - jekyll-last-modified-at
sass:
  sass_dir: static/_sass
syntax-highlighting:
  enabled : true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      organization-name: "NCBI"
      organization-url: "http://www.ncbi.nlm.nih.gov"
      organization-email: pubmedlabs@ncbi.nlm.nih.gov
      source-code-policy.url:
